keys:
  - &computer-mo age1yw3dt8myjpq3hek6gadzy8jd04l30ladgva7p74ktl7plfkwqs8qmk8c4x
  - &mo age1nkqrkx782x6hnn5l8trh2e4v5pgygkx2ql4w8m20pc9jzsq244zs8d44qw
  - &deck age18eu0gy9uhyeppljlq2faqnhlmtxmkx9up75x27h3mn5zrpz8ncgsf7fhfw
  - &nadine age14r5jdwjan0ft0zerz7jtgqlr7hzzcuruvqnyqfp3l48cr0jdwuhsqkj4sq
creation_rules:
  - path_regex: secrets.yaml$
    key_groups:
    - age:
      - *computer-mo
      - *mo
      - *deck
      - *nadine
