keys:
  - &master-host age1yaplz396e7kpdzckgf9x2jnmcuzwvp46rfrzhszsv6tsjam965lqstq0vc
  - &master-user age1nkqrkx782x6hnn5l8trh2e4v5pgygkx2ql4w8m20pc9jzsq244zs8d44qw
creation_rules:
  - path_regex: secrets.yaml$
    key_groups:
    - age:
      - *master-host
      - *master-user
