{ ... }: {
  flake.nixosModules.gnome-sys-gnome-apps = { pkgs, ...}:{
     environment.systemPackages = with pkgs; [
       dconf-editor
       adw-gtk3
       refine
       resources
       nautilus
       nautilus-python
       sushi
       gnome-text-editor
       gnome-console
       gnome-calculator
       loupe
       cine
       decibels
       tsukimi
       papers
       keypunch
       baobab
       turnon
       blanket
       kando
       impression
       high-tide
       gnome-disk-utility
       gnomeExtensions.dynamic-music-pill
       gnomeExtensions.appindicator
       gnomeExtensions.caffeine
       gnomeExtensions.clipboard-indicator
       gnomeExtensions.rounded-window-corners-reborn
       gnomeExtensions.night-theme-switcher
       gnomeExtensions.tinted-shell
       gnomeExtensions.middle-click-to-close-in-overview
       gnomeExtensions.quick-settings-audio-devices-hider
       gnomeExtensions.quick-settings-audio-devices-renamer
       gnomeExtensions.dash-to-dock
       gnomeExtensions.quick-settings-audio-panel
   ];
  };
}
